name: dart_utils
description: Dart Utils for MyLilius
version: 0.1.0
#homepage:

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart:  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

