name: dart_utils
description: Dart Utils for MyLilius
version: 0.1.0


environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  argon2: ^1.0.1
  bip32: ^2.0.0
  bip39: ^1.0.6
  encrypt: ^5.0.1
  hex: ^0.2.0
  pointycastle: ^3.5.2
  rxdart: ^0.27.3
  url_launcher: ^6.0.20
  web3dart:
    path: /Users/thegreataxios/MyLilius/web3dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test:

